// <auto-generated />
namespace BookStore.IdentityMigration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class removeUserFromOrder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeUserFromOrder));
        
        string IMigrationMetadata.Id
        {
            get { return "202312030437077_removeUserFromOrder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
